### ISSUE TITLE
Review Ticket [Week 2]

### ISSUE THREAD

**Issue by vardaansinha** [vardaansinha/FastPages#4]
**Notebook** for Python Quiz: [Link](https://vardaansinha.github.io/FastPages/jupyter/python/2022/08/28/pythonquiz.html)

For the Python quiz, I added an extra credit portion to get more than 100% and added an explanation for some issues and fixes for certain syntax that may be confusing.

**Tags** to help with Organization **(Extra Credit)**: [Link](https://vardaansinha.github.io/FastPages/categories/)

This also ties into the component of making the site useful for my other classes, as I have added a school tag in order to track my assignments and things to do for each class every week.

Vocabulary/Terms to Know **Page**: [Link](https://vardaansinha.github.io/FastPages/notes/)

I added some bash syntax to complete certain tasks in relation to Git.

Bash **Notebook** + Answers to **Hacks**: [Link](https://vardaansinha.github.io/FastPages/jupyter/bash/2022/08/28/bash.html)

I utilized many components of bash that can help to make the process of checking for tools and verifying versions much easier.

Personal Blog **Post** for Life: [Link](https://vardaansinha.github.io/FastPages/markdown/personal/2022/08/28/ap-exam-depression.html)

I added a 'personal' tag for any mental health related or personal life related posts.

**Post** with Images: [Link](https://vardaansinha.github.io/FastPages/markdown/personal/2022/08/28/pictures.html)

I chose my 3 favorite photos to use for a collage on this markdown post, and they went under the 'personal' tag.

Word Document **Post**: [Link](https://vardaansinha.github.io/FastPages/2022/08/28/Physics-Lab-Report.html)

This word document post was of my AP Physics Lab #1. It includes bullet points, tables, highlights, bold text, and images. 

I also added a small component to change the background color of my home page. In the future, I'd like to give each page a different color, and I want to change the font size and styling to make the site look more visually appealing.

Thanks!

**Comment by akshat122805** [comment]
Vardaan, you did a very good job, you completed the bash installations, created a quiz, imported a docx file, and even personalized your website more. I give you 2.8-3/3.  We should work on making the website look a bit cooler with CSS, and grade each other on which website looks better next week ;)

Also great job on making your CSP Notes more intricate.
