### ISSUE TITLE
Review Ticket: Week 4

### ISSUE THREAD

**Issue by vardaansinha** [vardaansinha/FastPages#6]
[My AppLab Creation:](https://studio.code.org/projects/applab/7hSXU7C0c_eWQbntswVx9aXQzVAbJtUE5x4LUGo7bSM)

The Week's Accomplishments:

1. Posted with the Outline of my AppLab Project
2. Created my AppLab Project, working with proper functionality.
3. Wrote a Post regarding the CollegeBoard requirements for the Performance Task & reflected on Bria's post on how to get a 5.
4. Explored ScrumBoard and posted regarding my findings & progress on ScrumBoard.

![image](https://user-images.githubusercontent.com/45215873/188574456-03d230da-8141-4aa1-b458-a240ae78ee7d.png)
Finally, I changed the FastPages social links to link to my GitHub profile instead, making it easier to access my FastPages repository directly from my site. 

[FastPages Link](https://vardaansinha.github.io/FastPages/)

Thanks!

**Comment by akshat122805** [comment]
I give you a solid 2.8, your quiz has a good source of functionality and does what it needs to. Your quiz is visually appealing and it also very interactive. I also give you a 2.8 because you coherently documented the process for the development of your quiz, so good job on that.

**Comment by jm1021** [comment]
A little confused on commit and change to local server.  This seemed a little off.   But efforts on video seem to show lots of command.  2.7
