### ISSUE TITLE
Review Ticket: Flask & Docker

### ISSUE THREAD

**Issue by vardaansinha** [vardaansinha/FastPages#7]
Here is the [link](https://youtu.be/0Gk5tNxeaD8) to my 1 minute video containing my Flask and Docker demonstrations in my site, and a brief review of the human-centered components of this week's hacks.

Here is the [link](https://vardaansinha.github.io/FastPages/markdown/csp/2022/09/19/collaboration.html) to my notes on the two CollegeBoard videos regarding collaboration. I included a screenshot of the quiz at the end, which was completed with my Scrum Team group.

Here is the [link](https://vardaansinha.github.io/FastPages/markdown/csp/2022/09/19/psychology.html) to the Psychology and the Good Life notes and takeaways. Our group went above and beyond and created a stress survey that got over 30 responses from our high-school peers, in order to assess the main problems and solutions regarding stress.

FastPages site: [https://vardaansinha.github.io/FastPages/](SITE)

[Group Flask Repository](https://github.com/DavidVasilev1/flask)

[Personal Flask Repository](https://github.com/vardaansinha/flaskportfolio)

Thanks!

**Comment by akshat122805** [comment]
You did a solid job on keeping the video short and going over all the aspects of the assignment. I looked more into your flask portfolio, and you did a great customizing the web server. Also I think we did a good job for creating the survey and establishing statistics for it. I give this a 2.7-2.8.

**Comment by TheoH32** [comment]
2.7+
Fast but effective
Said thought process thoroughly
Lengthy notes about mental health

**Comment by manigggg18** [comment]
2.7+

Clear notes and demonstration 

Additional material 

Sufficient video

**Comment by sanikasha** [comment]
2.7+
I like your concise but informative description, while still meeting the objective. Great productive blogging about psychology and collaboration in comp sci.

**Comment by rey444** [comment]
Great job! I think you deserve a 2.7+/3, because you had good customizations on your fastpages and flask repository, and you had great group collaboration with your psychology research. Your video was a bit difficult to hear, though.

**Comment by jiya-sav** [comment]
Vardaan deserves a 2.7+/3. He had a nice explanation for everything he did, and had extra notes and a survey about the psychology video.

**Comment by SamitPoojary** [comment]
I grade Vardaan to a 2.7+ because of how well he explained his understanding of everything.
