### ISSUE TITLE
Review Ticket: UI Starters

### ISSUE THREAD

**Issue by vardaansinha** [vardaansinha/FastPages#8]
1. Personalizing my index.html & stub (renamed)

![image](https://user-images.githubusercontent.com/45215873/192209586-028a8bea-b946-4e78-8b2d-cdc8603faf52.png)

![image](https://user-images.githubusercontent.com/45215873/192209699-b7b218de-861b-4761-aa0b-ffb5bc015ecd.png)

2. [Submenu](https://vardaansinha.github.io/FastPages/javascript/overview) Usage with a new page

3. [HTML + JavaScript Table](https://vardaansinha.github.io/FastPages/techtalk/javascript)

4. [JavaScript Algorithm](https://vardaansinha.github.io/FastPages/java/markdown/2022/09/25/js.html)

5. [Scrum Team PBL Project Plan](https://vardaansinha.github.io/FastPages/markdown/personal/2022/09/25/scrumteam.html)

6. My completed CB Quiz on Program Purpose and Function:

![image](https://user-images.githubusercontent.com/45215873/192210658-1b034004-96de-4333-8dfe-5f1007a3357f.png)

**Comment by jm1021** [comment]
Personalized cards on home page and had it links out to other information.   Added a new page and personalized the JavaScript draft year of QBs.  Nice random player and link.  2.9/3

**Comment by TheoH32** [comment]
2.7+
Good tasks
Random football player generator is creative and shows productiveness

**Comment by manigggg18** [comment]
2.7+

Organized Table setup and coding process

Regular blogging

Edited Stub and Flask

**Comment by kaiden-dough** [comment]
2.7+ Did all of the necessary requirements. I also like the project idea and the edited stub.html and index.html. Good Submenu. I like the Football cutting program for the Patriots
